language: java
jdk:
  - oraclejdk8

before_deploy:
  - mvn package
  - export DEB_FILE=$(ls target/ldap-password-reset-service*.dep)

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "${DEB_FILE}"
  skip_cleanup: true
  on:
    tags: true
